version: "3.8"


x-environment: &common_env
  RABBITMQ_DEFAULT_USER: testrabbitmquser
  RABBITMQ_DEFAULT_PASS: testsomepassword
  RABBITMQ_PORT: 5672

services:
  backend:
    build: .
    environment:
      <<: *common_env
      RABBITMQ_HOST: test_rabbitmq
    container_name: backend
    volumes:
      - ./:/app

    depends_on:
      - test_rabbitmq


  test_rabbitmq:
    image: rabbitmq:3.9
    environment:
      <<: *common_env
    container_name: rabbit
    restart: always
    ports:
      - 5672:5672
